@urlDev=http://localhost:3000

### 
GET {{urlDev}}/api/contacts/
### 
POST {{urlDev}}/api/contacts/
Content-Type: application/json

{
    "name":"gohohh43432",
    "email":"tanguyen@gmail",
    "address":"Can tho",
    "phone":"3232232"
}

###
DELETE  {{urlDev}}/api/contacts/

### find contacts by name
GET {{urlDev}}/api/contacts/?name=hhh
### find contacts by id 
GET http://localhost:3000/api/contacts/6421ba7357c89108a32cd3c9

# ### update contacts by id
# PUT {{urlDev}}/api/contacts/63b6bcb3989834d17e39a293
# Content-Type: application/json

# {
#     "name": "ghost updated 2"

